CREATE TABLE FRIENDS (
  U1 BIGINT NOT NULL ,
  U2 BIGINT NOT NULL ,
  CONSTRAINT PK_friends_id PRIMARY KEY (U1, U2),
  FOREIGN KEY (u1) REFERENCES USERS(ID),
  FOREIGN KEY (u1) REFERENCES USERS(ID),
);